export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCHFIELD';

export const REQEUST_ROBOTS_PENDING = 'REQEUST_ROBOTS_PENDING';
export const REQEUST_ROBOTS_SUCCESS = 'REQEUST_ROBOTS_SUCCESS';
export const REQEUST_ROBOTS_FAILED = 'REQEUST_ROBOTS_FAILED';